import http from 'node:http';
import { getIndexData, lastUpdated, publicBenchmarks } from './margin-data.js';
import { getEconomicOpportunities } from './opportunities.js';
import { discoverOpportunities } from './discovery-engine.js';
import { ingestLiveSignals, liveSignalSources } from './live-signal-ingestion.js';
import { landingPage, marginIndexPage } from './pages.js';

const VERSION = '0.8.0';
const port = Number(process.env.PORT || 3000);
const publicUrl = String(process.env.PUBLIC_URL || 'https://wealth-engine-production-e178.up.railway.app').replace(/\/$/, '');
const usage = { startedAt: new Date().toISOString(), calls: 0, capabilities: 0, index: 0, opportunities: 0, liveScans: 0, paidIntent: 0, mcp: 0 };
const headers={'access-control-allow-origin':'*','access-control-allow-headers':'content-type,mcp-session-id','content-security-policy':"default-src 'self'; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline'; img-src 'self' data:; form-action 'self'; base-uri 'none'; frame-ancestors 'none'",'x-content-type-options':'nosniff','x-frame-options':'DENY'};
function send(res,status,type,body,cache='no-store'){res.writeHead(status,{...headers,'content-type':type,'cache-control':cache});res.end(body)}
function json(res,status,payload,cache='no-store'){send(res,status,'application/json; charset=utf-8',JSON.stringify(payload),cache)}
function readJson(req){return new Promise((resolve,reject)=>{let raw='';req.setEncoding('utf8');req.on('data',c=>{raw+=c;if(raw.length>100000){reject(new Error('too_large'));req.destroy();}});req.on('end',()=>{try{resolve(JSON.parse(raw||'{}'))}catch{reject(new Error('invalid_json'))}});req.on('error',reject);});}
function mcpResult(id,result){return {jsonrpc:'2.0',id,result};} function mcpError(id,code,message){return {jsonrpc:'2.0',id,error:{code,message}};}
function voiceIndexPayload(){return {title:'Voice Margin Index',lastUpdated,plans:getIndexData(),publicBenchmarks};}
async function liveScan(){const ingestion=await ingestLiveSignals();return {...ingestion,opportunities:discoverOpportunities(ingestion.signals),policy:'Live discoveries are hypotheses derived automatically from fetched machine-readable market signals; they are not revenue forecasts.'};}
const offer={id:'voice-pricing-intelligence-founding',title:'Verified Voice-AI Pricing Intelligence — Founding Access',price:{amount:29,currency:'EUR',cadence:'month'},status:'paid-intent-test'};
const tools=[{name:'economic_opportunities',title:'Economic Opportunity Engine',description:'Rank economic opportunities from current structured evidence.',inputSchema:{type:'object',properties:{},additionalProperties:false}},{name:'live_market_scan',title:'Live Autonomous Market Scan',description:'Fetch machine-readable market data live and derive business opportunities without manually entering the signal.',inputSchema:{type:'object',properties:{},additionalProperties:false}},{name:'voice_margin_index',title:'Voice AI Margin Index',description:'Structured AI voice pricing benchmarks.',inputSchema:{type:'object',properties:{},additionalProperties:false}}];
const server=http.createServer(async(req,res)=>{const url=new URL(req.url||'/','http://localhost');if(req.method==='OPTIONS'){res.writeHead(204,{...headers,'access-control-allow-methods':'GET,POST,OPTIONS'});return res.end()}
if(req.method==='GET'&&url.pathname==='/health')return json(res,200,{ok:true,service:'wealth-engine',version:VERSION,updated:lastUpdated,liveSignalSources,usage});
if(req.method==='GET'&&url.pathname==='/api/live-scan'){usage.calls++;usage.liveScans++;return json(res,200,await liveScan());}
if(req.method==='GET'&&(url.pathname==='/api/opportunities'||url.pathname==='/opportunities.json')){usage.calls++;usage.opportunities++;return json(res,200,getEconomicOpportunities());}
if(req.method==='GET'&&(url.pathname==='/api/voice-margin-index'||url.pathname==='/voice-margin-index.json')){usage.calls++;usage.index++;return json(res,200,voiceIndexPayload());}
if(req.method==='GET'&&url.pathname==='/api/offers/voice-pricing-intelligence')return json(res,200,{...offer,intentUrl:`${publicUrl}/api/paid-intent`});
if(req.method==='POST'&&url.pathname==='/api/paid-intent'){usage.calls++;usage.paidIntent++;return json(res,202,{accepted:true,charged:false,offer:offer.id,price:offer.price});}
if(req.method==='GET'&&(url.pathname==='/.well-known/agent-capabilities.json'||url.pathname==='/capabilities')){usage.calls++;usage.capabilities++;return json(res,200,{name:'Wealth Engine',version:VERSION,description:'Autonomous economic-opportunity discovery engine.',capabilities:[{id:'live-market-scan',method:'GET',url:`${publicUrl}/api/live-scan`,price:'free'},{id:'economic-opportunities',method:'GET',url:`${publicUrl}/api/opportunities`,price:'free'},{id:'mcp',method:'POST',url:`${publicUrl}/mcp`,price:'free'}],mcp:`${publicUrl}/mcp`});}
if(req.method==='POST'&&url.pathname==='/mcp'){usage.calls++;usage.mcp++;try{const body=await readJson(req);const id=body.id??null;if(body.method==='initialize')return json(res,200,mcpResult(id,{protocolVersion:'2025-06-18',capabilities:{tools:{}},serverInfo:{name:'wealth-engine',version:VERSION},instructions:'Use live_market_scan to fetch current machine-readable market signals and derive opportunities autonomously.'}));if(body.method==='notifications/initialized')return send(res,202,'application/json; charset=utf-8','');if(body.method==='tools/list')return json(res,200,mcpResult(id,{tools}));if(body.method==='tools/call'&&body.params?.name==='live_market_scan'){const data=await liveScan();return json(res,200,mcpResult(id,{content:[{type:'text',text:JSON.stringify(data)}],structuredContent:data}));}if(body.method==='tools/call'&&body.params?.name==='economic_opportunities'){const data=getEconomicOpportunities();return json(res,200,mcpResult(id,{content:[{type:'text',text:JSON.stringify(data)}],structuredContent:data}));}if(body.method==='tools/call'&&body.params?.name==='voice_margin_index'){const data=voiceIndexPayload();return json(res,200,mcpResult(id,{content:[{type:'text',text:JSON.stringify(data)}],structuredContent:data}));}return json(res,200,mcpError(id,-32601,'Unsupported MCP method'));}catch{return json(res,400,mcpError(null,-32700,'Invalid request'));}}
if(req.method==='GET'&&url.pathname==='/usage')return json(res,200,usage);
if(req.method==='GET'&&url.pathname==='/')return send(res,200,'text/html; charset=utf-8',landingPage());
return json(res,404,{error:'Not found'});});server.listen(port,'0.0.0.0',()=>console.log(`wealth-engine listening on ${port}`));
